### ISSUE TITLE
Importing does not work

### ISSUE THREAD

**Issue by erez-rabih** [silverlyra/kubernetes-types#8]
hi

when I try to use a simple import as show in the example:
```typescript
import { ObjectMeta } from "kubernetes-types/meta/v1";
```
I get the following error
```
[eslint import/no-unresolved] [E] Unable to resolve path to module 'kubernetes-types/meta/v1'.
```

I have to use a `.d` suffeix to the v1 as follows:
```typescript
import { ObjectMeta } from "kubernetes-types/meta/v1.d";
```

should the docs be updated or I am just too noob to understand this?

**Comment by silverlyra** [comment]
(apologies for only seeing this now, but for reference –)

this was an error reported by `eslint`, not TypeScript. if you encounter this error, disabling the `import/no-unresolved` eslint rule would fix the issue.

I apologize for the lack of maintenance here; this package needs to be updated to modern `package.json` standards (#12)
